import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "@/assets/styles/common.less";
import "element-plus/es/components/message/style/css";
import MusicMask from "@/components/UI/music-mask.vue";
import MusicDialog from "@/components/UI/music-dialog.vue";
import MusicMessage from "@/components/UI/music-message.vue";
import MusicTabs from "@/components/UI/music-tabs.vue";
import Musicicon from "@/components/UI/music-icon.vue";
import MusicInfiniteLoading from "@/components/UI/music-infinite-loading.vue";
import MusicImage from "@/components/UI/music-image.vue";
import MusicButton from "@/components/UI/music-button.vue";
import MusicConfirm from "@/components/UI/music-confirm.vue";
import "default-passive-events";
const app = createApp(App);
app.component(MusicMask.name, MusicMask);
app.component(MusicDialog.name, MusicDialog);
app.component(MusicTabs.name, MusicTabs);
app.component(Musicicon.name, Musicicon);
app.component(MusicInfiniteLoading.name, MusicInfiniteLoading);
app.component(MusicMessage.name, MusicMessage);
app.component(MusicImage.name, MusicImage);
app.component(MusicButton.name, MusicButton);
app.component(MusicConfirm.name, MusicConfirm);
app.use(store).use(router).mount("#app");
